name: ProGuard Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up FAST-CLI
      run: |
        wget -q https://github.com/jewelshkjony/fast-cli/releases/download/v4.0.0/fast.zip
        unzip -q fast.zip -d fast-cli-temp
        rm fast.zip

    - name: Building project
      run: java -jar fast-cli-temp/fast.jar sync build -r -dir .

    - name: Cleanup FAST-CLI
      run: rm -rf fast-cli-temp
